version: "3"

services:
  otel-demo:
    build:
      context: ./
      dockerfile: ./OTELDemo/Dockerfile
    ports:
      - 80:80
    environment:
      - OTELDEMO_WEBAPI_URL=http://otel-demo-webapi
      - OTELDEMO_OTLP_ENPOINT=http://otel-collector:4318/v1/traces
  otel-demo-webapi:
    build:
      context: ./
      dockerfile: ./OTELDemo.WebAPI/Dockerfile
    environment:
      - OTELDEMO_OTLP_ENPOINT=http://otel-collector:4318/v1/traces
    ports:
      - 8080:80



  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./configs/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - 8888:8888   # Prometheus metrics exposed by the collector
      - 8889:8889   # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317   # grpc
      - 4318:4318   # http
    depends_on:
      - jaeger

