{
 "title": "OpenTelemetry ASP.NET Core Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Кол-во запросов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_duration_ms_count{}",
     "legendFormat": "{{http_method}} {{instance}}/{{http_target}} - {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Доступность сервисов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "95й перцентиль длительности",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_ms_bucket[5m])) by (le,instance,http_method,http_target))",
     "legendFormat": "{{http_method}} {{instance}}/{{http_target}}"
    }
   ]
  }
 ]
}