receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:
  attributes:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: ActionName, TraceId, SpanId

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [loki]
      processors: [attributes, batch]