global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:
alerting:

scrape_configs:
  - job_name: "otel-demo-apps"
    static_configs:
      - targets: ["otel-demo:80", "otel-demo-webapi:80"]
